### ISSUE TITLE
[Feature] Create Facebook event from event ABR option.

### ISSUE THREAD

**Issue by lpoulter** [madarasz/always-be-running#28]
Would use the facebook api to create an event when or after you create a ABR event.

**Comment by madarasz** [comment]
In order to create an FB event you need a FB account/app, lets call it "ABR FB bot". The whole process is a bit complicated. Also TOs might want to modify the event, participants might want to ask from the FB host of the event. You cannot really give users access to "ABR FB bot".

There is a better way to avoid duplicate work on ABR and FB. How about I add an "Import from FB event" button. You give it an FB event link and it can get the title, date, location, description of the event. It might even try to guess to tournament type from the event title. How about that?

**Comment by lpoulter** [comment]
Yeah thats a good idea.

**Comment by madarasz** [comment]
Should work now. There is an "Create from FB event" button on the Organise page.
