### ISSUE TITLE
[BUG] Import from NRTM fails

### ISSUE THREAD

**Issue by lpoulter** [madarasz/always-be-running#38]
A user has reported that the import fails. This is on both iphone and firefox and with two different Collusion codes.

Error message: 'the code has expired' or whoops looks like something went wrong.
Event: https://alwaysberunning.net/tournaments/229/new-season-gnk-at-dice-donuts
User: rftq
iPhone
NRTM v1.40
Collusion code: 391953

![image](https://cloud.githubusercontent.com/assets/3940567/21927961/1b84ee7a-d980-11e6-8fca-65cac26ffffb.png)

**Comment by madarasz** [comment]
Thx for the bugreport.

Digged into it, the problem is that player "Mark" has no corp identity set. I will add error handling soon. In the meantime try to add the missing data and reupload if possible.

You will get "code expired" if you have already tried to use the conclusion code, it's one time only. Reuploading helps.

**Comment by madarasz** [comment]
Error handling added. In such case, TO should see this:
![Imgur](http://i.imgur.com/qamyOZ7.png)
