### ISSUE TITLE
[Feature Request] Connecting "series" of tournaments

### ISSUE THREAD

**Issue by ANR-PeterPan** [madarasz/always-be-running#49]
What about a <prev> / <next> link possibility to connect  recurring tournaments like the monthly gnk in city a or, in my case, the bankjob-tournaments or to connect store-/ regional-championships in a specific country/state?

**Comment by madarasz** [comment]
Thx for sharing your idea.

Though, I will mark this with low priority because I don't see much added value for the player or the TO. Where would you put this information on the UI? On the tournament details page, it's fine, you list tournaments from the same group in a box. Other than that I see no place for this in the Upcoming or the Results page.

The store/regionals tournaments of a country can be summed up by filtering on the Upcoming or Results page.

As a workaround I suggest you add links in the tournament description for the other connected tournaments.

**Comment by ANR-PeterPan** [comment]
Yes, I thought to implement this on the tournament-detail page. Perhaps in a small box between "Location" and "QR-Code" like

<next> This tournament is part of a series <prev>

The player could cycle through the details of the tournaments in this series by clicking the buttons without switching to upcoming/results page, f.e. switching from May GNK to April GNK by clicking <prev> or to June GNK by clicking <next> in case of a recurring tournament, which was my original idea.
Also you could use this feature to link Stores/Regionals of a special area, f.e. a country. They could even be connected in a cycle by linking the "first" one as <next> of the "last" one and vice versa regarding the <prev>. This could be useful during the season, when some are in upcoming and some are in results.

When connecting a tournament on a detail page as a <prev>-one you could (or should) automaticly add the tournament-number as a <next> of the selected tournament (if it is still available), perhaps with confirming by the TO if he/she is not the same. Deletions should also be on both.

**Comment by madarasz** [comment]
I added "Tournament Groups". You can find it under the Organise page >> Tournament Group tabs. Try it out, let me know what you think on Slack :)
